service: serviceNameA

provider:
  name: aws
  runtime: nodejs4.3

package:
  exclude:
    - test/**
    - .git/**
    - coverage/**

functions:
  functionA:
    handler: functions/functionA/functionA.handler
    events:
      - http:
          path: pathAB
          method: GET
      - http:
          path: pathAB
          method: POST
  functionB:
    handler: functions/functionB/functionB.handler
    events:
      - http:
          path: pathBA
          method: GET
      - http:
          path: pathBA
          method: POST

plugins:
  - serverless-offline
