service: serviceName

provider:
  name: aws
  runtime: nodejs4.3

package:
  exclude:
    - tests/**
    - .git/**

functions:
  functionA:
    handler: functions/functionA/functionA.handler
    events:
      - http:
          path: pathA
          method: GET
      - http:
          path: pathA
          method: POST
  functionB:
    handler: functions/functionB/functionB.handler
    events:
      - http:
          path: pathB
          method: GET
      - http:
          path: pathB
          method: POST

plugins:
  - serverless-offline
